# Generated by Django 2.2.2 on 2019-06-04 09:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Catalog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('parent_catalog', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.Catalog')),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=128)),
                ('extension', models.CharField(max_length=20)),
                ('date_upload', models.DateTimeField(auto_now_add=True)),
                ('dir', models.FileField(upload_to='files/')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('catalog_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Catalog')),
            ],
        ),
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_nr', models.CharField(max_length=30)),
                ('changes', models.TextField()),
                ('file_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.File')),
            ],
        ),
        migrations.CreateModel(
            name='Repository',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('is_public', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Repositories',
            },
        ),
        migrations.AddField(
            model_name='file',
            name='repository_Id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Repository'),
        ),
        migrations.AddField(
            model_name='catalog',
            name='repository_Id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Repository'),
        ),
    ]
