# Generated by Django 2.2.2 on 2019-06-04 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='version',
            name='changes',
        ),
        migrations.AlterField(
            model_name='version',
            name='version_nr',
            field=models.IntegerField(),
        ),
    ]
