# Generated by Django 2.1.7 on 2019-05-03 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20190409_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalog',
            name='parent_catalog',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.Catalog'),
        ),
    ]
