# Generated by Django 2.1.7 on 2019-06-03 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20190526_1600'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='extention',
            new_name='extension',
        ),
    ]
