# Generated by Django 2.1.7 on 2019-06-03 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20190526_1600'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='content',
        ),
        migrations.AddField(
            model_name='file',
            name='dir',
            field=models.FileField(default=0, upload_to='files/'),
            preserve_default=False,
        ),
    ]
