# Generated by Django 2.1.7 on 2019-06-03 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20190603_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='date_upload',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
